version: '3.9'

services:
  backend:
    build:
      context: ./backend/FlightBoard.Api
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - frontend
    volumes:
      - ./backend/FlightBoard.Api/flightboard.db:/app/flightboard.db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend