
services:
  backend:
    build:
      context: ./backend
      dockerfile: FlightBoard.Api/Dockerfile
    ports:
      - "5000:80"
    container_name: flightboard-backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - flightboard_data:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    container_name: flightboard-frontend

volumes:
  flightboard_data: